# First-boot script generation for post-install configuration
# shellcheck shell=bash

firstboot_generate() {
    local working_dir="${PVE_WORKING_DIR:-/root}"
    local output_dir="${working_dir}/generated"
    local output_file="${output_dir}/first-boot.sh"

    mkdir -p "$output_dir"

    log_info "Generating first-boot script..."

    local iface="${PVE_PREDICTED_IFACE:-${PVE_INTERFACE}}"
    local dns_line=""
    for dns in $PVE_DNS_SERVERS; do
        dns_line+="nameserver ${dns}"$'\n'
    done

    # Build the interfaces file content
    local interfaces_content
    interfaces_content="$(firstboot_render_interfaces)"

    # Build the hosts file content
    local hosts_content
    hosts_content="$(firstboot_render_hosts)"

    # Build the sysctl content
    local sysctl_content="net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1"

    cat > "$output_file" <<'FBHEADER'
#!/bin/bash
# Proxmox VE First-Boot Configuration Script
# Generated by pve-install.sh -- do not edit manually
set -euo pipefail

LOG="/var/log/pve-first-boot.log"
exec > >(tee -a "$LOG") 2>&1
echo "[$(date)] First-boot configuration starting..."

FBHEADER

    cat >> "$output_file" <<FBNET
# --- Network Interfaces ---
cat > /etc/network/interfaces <<'INTERFACES_EOF'
${interfaces_content}
INTERFACES_EOF
echo "[$(date)] Network interfaces configured"

FBNET

    cat >> "$output_file" <<FBHOSTS
# --- Hostname ---
echo "${PVE_HOSTNAME}" > /etc/hostname
hostnamectl set-hostname "${PVE_HOSTNAME}" 2>/dev/null || true

cat > /etc/hosts <<'HOSTS_EOF'
${hosts_content}
HOSTS_EOF
echo "[$(date)] Hostname and hosts configured"

FBHOSTS

    cat >> "$output_file" <<FBDNS
# --- DNS ---
cat > /etc/resolv.conf <<'DNS_EOF'
${dns_line}DNS_EOF
echo "[$(date)] DNS configured"

FBDNS

    cat >> "$output_file" <<FBSYSCTL
# --- Sysctl ---
cat > /etc/sysctl.d/99-proxmox.conf <<'SYSCTL_EOF'
${sysctl_content}
SYSCTL_EOF
sysctl -p /etc/sysctl.d/99-proxmox.conf >/dev/null 2>&1 || true
echo "[$(date)] Sysctl configured"

FBSYSCTL

    cat >> "$output_file" <<'FBAPT'
# --- APT Sources ---
# Remove enterprise subscription repo if present
if [ -f /etc/apt/sources.list.d/pve-enterprise.list ]; then
    mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.disabled
fi

# Backup original sources.list if it exists
if [ -f /etc/apt/sources.list ] && [ -s /etc/apt/sources.list ]; then
    mv /etc/apt/sources.list /etc/apt/sources.list.bak
fi
echo "[$(date)] APT sources configured"

FBAPT

    cat >> "$output_file" <<'FBSERVICES'
# --- Services ---
systemctl disable --now rpcbind rpcbind.socket 2>/dev/null || true
echo "[$(date)] Unnecessary services disabled"

FBSERVICES

    cat >> "$output_file" <<'FBSUB'
# --- Remove Subscription Nag ---
PROXMOXLIB="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
if [ -f "$PROXMOXLIB" ]; then
    sed -Ezi.bak \
        "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" \
        "$PROXMOXLIB"
    systemctl restart pveproxy.service 2>/dev/null || true
    echo "[$(date)] Subscription notice removed"
fi

FBSUB

    cat >> "$output_file" <<'FBDONE'
echo "[$(date)] First-boot configuration complete!"
echo "System is ready. Access web UI at https://$(hostname -I | awk '{print $1}'):8006"
FBDONE

    chmod +x "$output_file"
    ui_success "First-boot script generated"
    log_debug "First-boot script: ${output_file}"
}

firstboot_render_interfaces() {
    local iface="${PVE_PREDICTED_IFACE:-${PVE_INTERFACE}}"

    cat <<IFACES
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

iface lo inet6 loopback

iface ${iface} inet manual

auto vmbr0
iface vmbr0 inet static
    address ${PVE_MAIN_IPV4_CIDR}
    gateway ${PVE_MAIN_IPV4_GW}
    bridge-ports ${iface}
    bridge-stp off
    bridge-fd 1
    bridge-vlan-aware yes
    bridge-vids 2-4094
    pointopoint ${PVE_MAIN_IPV4_GW}
$(if [[ -n "$PVE_IPV6_CIDR" ]]; then
cat <<IPV6

iface vmbr0 inet6 static
    address ${PVE_IPV6_CIDR}
    gateway fe80::1
IPV6
fi)
$(if [[ -n "$PVE_PRIVATE_IP_CIDR" ]]; then
cat <<VMBR1

auto vmbr1
iface vmbr1 inet static
    address ${PVE_PRIVATE_IP_CIDR}
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    post-up   iptables -t nat -A POSTROUTING -s '${PVE_PRIVATE_SUBNET}' -o vmbr0 -j MASQUERADE
    post-down iptables -t nat -D POSTROUTING -s '${PVE_PRIVATE_SUBNET}' -o vmbr0 -j MASQUERADE
    post-up   iptables -t raw -I PREROUTING -i fwbr+ -j CT --zone 1
    post-down iptables -t raw -D PREROUTING -i fwbr+ -j CT --zone 1
VMBR1
fi)
$(if [[ -n "$PVE_FIRST_IPV6_CIDR" ]]; then
cat <<IPV6B

iface vmbr1 inet6 static
    address ${PVE_FIRST_IPV6_CIDR}
IPV6B
fi)
IFACES
}

firstboot_render_hosts() {
    cat <<HOSTS
127.0.0.1 localhost.localdomain localhost
${PVE_MAIN_IPV4} ${PVE_FQDN} ${PVE_HOSTNAME}

# IPv6
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
$(if [[ -n "$PVE_IPV6" ]]; then
echo "${PVE_IPV6} ${PVE_FQDN} ${PVE_HOSTNAME}"
fi)
HOSTS
}

# Check if first-boot hooks are supported by checking the ISO version
firstboot_is_supported() {
    if ! command -v proxmox-auto-install-assistant &>/dev/null; then
        return 1
    fi

    if proxmox-auto-install-assistant prepare-iso --help 2>&1 | grep -q 'on-first-boot'; then
        return 0
    fi

    return 1
}
