# First-boot script generation for post-install configuration
# shellcheck shell=bash

firstboot_generate() {
    local working_dir="${PVE_WORKING_DIR:-/root}"
    local output_dir="${working_dir}/generated"
    local output_file="${output_dir}/first-boot.sh"

    mkdir -p "$output_dir"

    log_info "Generating first-boot script..."

    local iface="${PVE_PREDICTED_IFACE:-${PVE_INTERFACE}}"
    local dns_line=""
    for dns in $PVE_DNS_SERVERS; do
        dns_line+="nameserver ${dns}"$'\n'
    done

    # Build the interfaces file content
    local interfaces_content
    interfaces_content="$(firstboot_render_interfaces)"

    # Build the hosts file content
    local hosts_content
    hosts_content="$(firstboot_render_hosts)"

    # Build the sysctl content
    local sysctl_content="net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1"

    # Add conntrack tuning for NAT setups (prevents exhaustion with many VMs)
    if [[ "$PVE_NETWORK_MODE" == "nat" ]]; then
        sysctl_content+="
net.netfilter.nf_conntrack_max=1048576
net.netfilter.nf_conntrack_tcp_timeout_established=28800"
    fi

    cat > "$output_file" <<'FBHEADER'
#!/bin/bash
# Proxmox VE First-Boot Configuration Script
# Generated by pve-install.sh -- do not edit manually
set -euo pipefail

LOG="/var/log/pve-first-boot.log"
exec > >(tee -a "$LOG") 2>&1
echo "[$(date)] First-boot configuration starting..."

FBHEADER

    cat >> "$output_file" <<FBNET
# --- Network Interfaces ---
cat > /etc/network/interfaces <<'INTERFACES_EOF'
${interfaces_content}
INTERFACES_EOF
echo "[$(date)] Network interfaces configured"

FBNET

    cat >> "$output_file" <<FBHOSTS
# --- Hostname ---
echo "${PVE_HOSTNAME}" > /etc/hostname
hostnamectl set-hostname "${PVE_HOSTNAME}" 2>/dev/null || true

cat > /etc/hosts <<'HOSTS_EOF'
${hosts_content}
HOSTS_EOF
echo "[$(date)] Hostname and hosts configured"

FBHOSTS

    cat >> "$output_file" <<FBDNS
# --- DNS ---
cat > /etc/resolv.conf <<'DNS_EOF'
${dns_line}DNS_EOF
echo "[$(date)] DNS configured"

FBDNS

    cat >> "$output_file" <<FBSYSCTL
# --- Sysctl ---
cat > /etc/sysctl.d/99-proxmox.conf <<'SYSCTL_EOF'
${sysctl_content}
SYSCTL_EOF
sysctl -p /etc/sysctl.d/99-proxmox.conf >/dev/null 2>&1 || true
echo "[$(date)] Sysctl configured"

FBSYSCTL

    # ZFS ARC tuning (only for ZFS installs)
    if [[ "$PVE_FILESYSTEM" == "zfs" ]]; then
        # Calculate ARC limits based on total RAM:
        # arc_min = ~5% of RAM (floor for cache, prevents thrashing)
        # arc_max = ~15% of RAM (generous but leaves room for VMs)
        # Uses PVE_ZFS_ARC_MAX from config if explicitly set
        local total_ram_gb=$(( PVE_QEMU_RAM_MB / 1024 * 4 / 3 ))  # approximate host RAM from QEMU alloc
        if [[ -f /proc/meminfo ]]; then
            local total_kb
            total_kb="$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}')"
            total_ram_gb=$(( total_kb / 1024 / 1024 ))
        fi

        local arc_min_gb=$(( total_ram_gb * 5 / 100 ))
        local arc_max_gb=$(( total_ram_gb * 15 / 100 ))
        # Enforce sane minimums
        if (( arc_min_gb < 1 )); then arc_min_gb=1; fi
        if (( arc_max_gb < 2 )); then arc_max_gb=2; fi
        # Use explicit override if provided
        if [[ -n "$PVE_ZFS_ARC_MAX" ]]; then
            arc_max_gb=$(( PVE_ZFS_ARC_MAX / 1024 ))
        fi

        local arc_min_bytes=$(( arc_min_gb * 1024 * 1024 * 1024 ))
        local arc_max_bytes=$(( arc_max_gb * 1024 * 1024 * 1024 ))

        cat >> "$output_file" <<FBZFS
# --- ZFS ARC Memory Tuning ---
# Host RAM: ~${total_ram_gb} GB -> ARC min: ${arc_min_gb} GB, max: ${arc_max_gb} GB
rm -f /etc/modprobe.d/zfs.conf
cat > /etc/modprobe.d/99-zfs.conf <<'ZFS_EOF'
options zfs zfs_arc_min=${arc_min_bytes}
options zfs zfs_arc_max=${arc_max_bytes}
ZFS_EOF
update-initramfs -u -k all >/dev/null 2>&1 || true
echo "[\$(date)] ZFS ARC tuned: min=${arc_min_gb}GB max=${arc_max_gb}GB"

FBZFS
    fi

    # nf_conntrack module for NAT
    if [[ "$PVE_NETWORK_MODE" == "nat" ]]; then
        cat >> "$output_file" <<'FBCONNTRACK'
# --- Conntrack Module ---
if ! grep -q '^nf_conntrack$' /etc/modules 2>/dev/null; then
    echo "nf_conntrack" >> /etc/modules
fi
modprobe nf_conntrack 2>/dev/null || true
echo "[$(date)] nf_conntrack module configured"

FBCONNTRACK
    fi

    cat >> "$output_file" <<FBAPT
# --- APT Sources ---
# Disable ALL enterprise repos (require paid subscription).
# Proxmox uses various filenames across versions:
#   pve-enterprise.list, ceph.list          (legacy .list format)
#   pve-enterprise.sources, ceph.sources    (DEB822 .sources format)
# Also catch any file containing enterprise.proxmox.com
for f in /etc/apt/sources.list.d/pve-enterprise.list \
         /etc/apt/sources.list.d/pve-enterprise.sources \
         /etc/apt/sources.list.d/ceph.list \
         /etc/apt/sources.list.d/ceph.sources; do
    if [ -f "\$f" ]; then
        mv "\$f" "\${f}.disabled"
        echo "[\$(date)] Disabled enterprise repo: \$f"
    fi
done

# Catch any remaining files that reference enterprise.proxmox.com
for f in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
    if [ -f "\$f" ] && grep -q 'enterprise.proxmox.com' "\$f" 2>/dev/null; then
        mv "\$f" "\${f}.disabled"
        echo "[\$(date)] Disabled enterprise repo: \$f"
    fi
done

# Backup original sources.list if it exists
if [ -f /etc/apt/sources.list ] && [ -s /etc/apt/sources.list ]; then
    mv /etc/apt/sources.list /etc/apt/sources.list.bak
fi

# Add Proxmox no-subscription repos (PVE + Ceph)
cat > /etc/apt/sources.list.d/pve-no-subscription.list <<'PVEREPO_EOF'
deb http://download.proxmox.com/debian/pve ${PVE_DEBIAN_SUITE} pve-no-subscription
PVEREPO_EOF

cat > /etc/apt/sources.list.d/ceph-no-subscription.list <<'CEPHREPO_EOF'
deb http://download.proxmox.com/debian/ceph-squid ${PVE_DEBIAN_SUITE} no-subscription
CEPHREPO_EOF

echo "[\$(date)] APT sources configured (no-subscription repos for PVE + Ceph)"

FBAPT

    cat >> "$output_file" <<'FBSERVICES'
# --- Services ---
systemctl disable --now rpcbind rpcbind.socket 2>/dev/null || true
echo "[$(date)] Unnecessary services disabled"

FBSERVICES

    cat >> "$output_file" <<'FBSUB'
# --- Remove Subscription Nag ---
PROXMOXLIB="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
if [ -f "$PROXMOXLIB" ]; then
    sed -Ezi.bak \
        "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" \
        "$PROXMOXLIB"
    systemctl restart pveproxy.service 2>/dev/null || true
    echo "[$(date)] Subscription notice removed"
fi

FBSUB

    # --- SSH Hardening (only if keys were provided) ---
    if [[ -n "$PVE_SSH_KEYS" ]]; then
        # Write keys into the script as a heredoc
        local escaped_keys
        escaped_keys="$(echo "$PVE_SSH_KEYS" | sed 's/\\/\\\\/g')"

        cat >> "$output_file" <<FBSSH
# --- SSH Hardening ---
mkdir -p /root/.ssh
chmod 700 /root/.ssh

cat > /root/.ssh/authorized_keys <<'SSHKEYS_EOF'
${escaped_keys}
SSHKEYS_EOF
chmod 600 /root/.ssh/authorized_keys

# Proxmox cluster-synced authorized_keys (available after pmxcfs starts)
if [ -d /etc/pve/priv ]; then
    cp /root/.ssh/authorized_keys /etc/pve/priv/authorized_keys
    echo "[\\$(date)] SSH keys installed to /etc/pve/priv/authorized_keys (cluster-synced)"
fi

# Drop-in config -- does not modify the main sshd_config
cat > /etc/ssh/sshd_config.d/99-hardening.conf <<'SSHD_EOF'
# Proxmox-safe SSH hardening (cluster-compatible)
# PermitRootLogin must be prohibit-password, NOT no (breaks clustering)
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
MaxAuthTries 3
X11Forwarding no
SSHD_EOF

systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null || true
echo "[\\$(date)] SSH hardened: password login disabled, key-only access"

FBSSH
    else
        cat >> "$output_file" <<'FBSSH_SKIP'
# --- SSH Hardening SKIPPED ---
# No SSH keys were provided during installation.
# Password login remains enabled. To harden later:
#   1. Add your public key to /root/.ssh/authorized_keys
#   2. Copy to /etc/pve/priv/authorized_keys (for cluster sync)
#   3. Create /etc/ssh/sshd_config.d/99-hardening.conf with:
#        PermitRootLogin prohibit-password
#        PasswordAuthentication no
#   4. systemctl restart sshd
echo "[$(date)] SSH hardening skipped (no keys provided)"

FBSSH_SKIP
    fi

    cat >> "$output_file" <<'FBDONE'
echo "[$(date)] First-boot configuration complete!"
echo "System is ready. Access web UI at https://$(hostname -I | awk '{print $1}'):8006"
FBDONE

    chmod +x "$output_file"
    ui_success "First-boot script generated"
    log_debug "First-boot script: ${output_file}"
}

firstboot_render_interfaces() {
    local iface="${PVE_PREDICTED_IFACE:-${PVE_INTERFACE}}"

    cat <<IFACES
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

iface lo inet6 loopback

iface ${iface} inet manual

auto vmbr0
iface vmbr0 inet static
    address ${PVE_MAIN_IPV4_CIDR}
    gateway ${PVE_MAIN_IPV4_GW}
    bridge-ports ${iface}
    bridge-stp off
    bridge-fd 1
    bridge-vlan-aware yes
    bridge-vids 2-4094
    pointopoint ${PVE_MAIN_IPV4_GW}
$(if [[ -n "$PVE_IPV6_CIDR" ]]; then
cat <<IPV6

iface vmbr0 inet6 static
    address ${PVE_IPV6_CIDR}
    gateway fe80::1
IPV6
fi)
$(if [[ -n "$PVE_PRIVATE_IP_CIDR" ]]; then
cat <<VMBR1

auto vmbr1
iface vmbr1 inet static
    address ${PVE_PRIVATE_IP_CIDR}
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    post-up   iptables -t nat -A POSTROUTING -s '${PVE_PRIVATE_SUBNET}' -o vmbr0 -j MASQUERADE
    post-down iptables -t nat -D POSTROUTING -s '${PVE_PRIVATE_SUBNET}' -o vmbr0 -j MASQUERADE
    post-up   iptables -t raw -I PREROUTING -i fwbr+ -j CT --zone 1
    post-down iptables -t raw -D PREROUTING -i fwbr+ -j CT --zone 1
VMBR1
fi)
$(if [[ -n "$PVE_FIRST_IPV6_CIDR" ]]; then
cat <<IPV6B

iface vmbr1 inet6 static
    address ${PVE_FIRST_IPV6_CIDR}
IPV6B
fi)
IFACES
}

firstboot_render_hosts() {
    cat <<HOSTS
127.0.0.1 localhost.localdomain localhost
${PVE_MAIN_IPV4} ${PVE_FQDN} ${PVE_HOSTNAME}

# IPv6
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
$(if [[ -n "$PVE_IPV6" ]]; then
echo "${PVE_IPV6} ${PVE_FQDN} ${PVE_HOSTNAME}"
fi)
HOSTS
}

# Check if first-boot hooks are supported by checking the ISO version
firstboot_is_supported() {
    if ! command -v proxmox-auto-install-assistant &>/dev/null; then
        return 1
    fi

    if proxmox-auto-install-assistant prepare-iso --help 2>&1 | grep -q 'on-first-boot'; then
        return 0
    fi

    return 1
}
