#!/bin/bash
# Proxmox VE First-Boot Configuration Script
# Placeholders: {{HOSTNAME}}, {{INTERFACES_CONTENT}}, {{HOSTS_CONTENT}},
#               {{DNS_CONTENT}}, {{SYSCTL_CONTENT}}
# Generated by pve-install.sh -- do not edit manually
set -euo pipefail

LOG="/var/log/pve-first-boot.log"
exec > >(tee -a "$LOG") 2>&1
echo "[$(date)] First-boot configuration starting..."

# --- Network Interfaces ---
cat > /etc/network/interfaces <<'INTERFACES_EOF'
{{INTERFACES_CONTENT}}
INTERFACES_EOF
echo "[$(date)] Network interfaces configured"

# --- Hostname ---
echo "{{HOSTNAME}}" > /etc/hostname
hostnamectl set-hostname "{{HOSTNAME}}" 2>/dev/null || true

cat > /etc/hosts <<'HOSTS_EOF'
{{HOSTS_CONTENT}}
HOSTS_EOF
echo "[$(date)] Hostname and hosts configured"

# --- DNS ---
cat > /etc/resolv.conf <<'DNS_EOF'
{{DNS_CONTENT}}
DNS_EOF
echo "[$(date)] DNS configured"

# --- Sysctl ---
cat > /etc/sysctl.d/99-proxmox.conf <<'SYSCTL_EOF'
{{SYSCTL_CONTENT}}
SYSCTL_EOF
sysctl -p /etc/sysctl.d/99-proxmox.conf >/dev/null 2>&1 || true
echo "[$(date)] Sysctl configured"

# --- APT Sources ---
if [ -f /etc/apt/sources.list.d/pve-enterprise.list ]; then
    mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.disabled
fi
if [ -f /etc/apt/sources.list ] && [ -s /etc/apt/sources.list ]; then
    mv /etc/apt/sources.list /etc/apt/sources.list.bak
fi
echo "[$(date)] APT sources configured"

# --- Services ---
systemctl disable --now rpcbind rpcbind.socket 2>/dev/null || true
echo "[$(date)] Unnecessary services disabled"

# --- Remove Subscription Nag ---
PROXMOXLIB="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
if [ -f "$PROXMOXLIB" ]; then
    sed -Ezi.bak \
        "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" \
        "$PROXMOXLIB"
    systemctl restart pveproxy.service 2>/dev/null || true
    echo "[$(date)] Subscription notice removed"
fi

echo "[$(date)] First-boot configuration complete!"
